### ISSUE TITLE
nothing is even vaguely responsive

### ISSUE THREAD

**Issue by woodwardtw** [woodwardtw/openlearninghub#3] opened 2016-11-17 02:33 UTC
it is like a dead frozen rock that has never been warm

**Comment by cogdog** [comment] 2016-11-17 02:44
Yeah I know. To me it's a deal killer, but G is so in love with it. That's why i asked him to look at the site on a small screen.

**Comment by woodwardtw** [comment] 2016-11-17 13:22
Took me a bit to figure out a chunk of CSS was being set via the Woo Themes custom CSS panel. I couldn't figure out why my stuff was failing . . . . There's still some stuff in there on the live site in case you get in a similar position.

**Comment by cogdog** [comment] 2016-11-17 14:27
I copied the settings last night from the TV site and there was custom CSS in that panel; I'll move it to the style sheet and not use that panel

**Comment by GardnerCampbell** [comment] 2016-11-21 12:51
"On the theme front, to be honest, you could reuse the thoughtvectors theme, which is going to be easiest route, and you are familiar with the way it works. The lack of mobile is not really a show stopper, it is just a very small version of the site." This was the word eight days ago. When Tom brought up the Dazzling theme as a possibility, and I engaged with his suggestion, the response was "Look, there are many wild, great things we could do. But this is a fast track project, and my attention space is rather limited. Let's just get this done ? Gardner is very comfortable and liking the TV theme. If you can look it it on a phone or tablet, and be okay with that, let's just roll it out."

I missed the request to look at the site on a small screen; my apologies. I can't see that it matters much if the desire is to go the simplest and most direct route. I can't quarrel with that desire, and I won't, because it's true that this work is being done for next to no money. So yes, let's just get it over with. No wild great things needed.

**Comment by GardnerCampbell** [comment] 2016-11-21 13:23
asdas

**Comment by cogdog** [comment] 2016-11-21 13:59
Alan revised that thought! It was worth it to give the old theme a try before concluding. The pluses are our familiarity with it and a good amount of stuff we can reuse. 

It will not be the best experience on a mobile but Tom has been doing good stuff to help remedy it.

Onwards...

**Comment by GardnerCampbell** [comment] 2016-11-22 19:35
I'm adding content to the site now. Lots of great little touches; thank you. Some early questions/observations:

1. I can't add my blog via FWP. Is that operator error, or is that method disabled so the "Join Up" function works?

2. I'm using Chrome at default zoom level on my desktop PC to view the site just now. The fonts are small and the site is fixed width. I am assuming this is done deliberately to enhance the mobile experience--is that true? If so, the site isn't going to be very usable from the desktop, which I imagine will be one of the primary modes for our demographic. Please advise.

**Comment by woodwardtw** [comment] 2016-11-22 19:49
1. Are you joining via the form at http://openlearninghub.net/syndicate-here/? http://openlearninghub.net/syndicate-here/? I was able to join via that method without issue. 
2. To my knowledge the theme has always been fixed width. Any customization I did for mobile is applied at the sub 760 px width zone and would make the font larger rather than smaller. I can’t see any difference in presentation between the current site and the thoughtvectors site on a Mac (10.11.6) and in Chrome (Canary & 54.0), FF, and Safari on a laptop. Maybe throw a screenshot with some additional browser details up?

**Comment by cogdog** [comment] 2016-11-22 19:57
> I can't add my blog via FWP. Is that operator error, or is that method disabled so the "Join Up" function works?

I meant to tell you earlier, I saw that same error ("curl failed") - this is where your web host is blocking the way that FWP gets feed info, often when web hosts turn off something called XML-RPC to reduce attacks. It is not very common But I cannot be sure that is the reason, is your blog still on Bluehost? The end around often for problems with these kind of feed communication issues is to set up a FeedBurner for your feed, and use that URL (do not add Feedburner to your blog, just use the web service) it tends to "clean" things that cause issues with FWP.

Nothing in my code blocks direct adds to FWP, but if you do there is a manual edit you will need to do in the Links entry, this will be added very soon to the docs. I would recommend not adding directly, but use the form, because it is set up to create the author account based on the twitter name.

This theme was designed pre-Responsive era, and we made the decision to use it since you had no problem using the Thoughtvectors site.  We can mod the theme to bump the font size, but the fixed width is .... fixed. Hence why we asked about picking a new theme.

If you cant live with this, let's find one ASAP that will not require a lot of hacking. It needs to be responsive, have a top featured post slider, and ways of front page displaying different slices of content (by category or tag). The format of single posts matters less as most links go out. I'd guess a front "masonry" display of posts. 

I do think the Covering the Coverage theme can work... it's not as much different display on the front, but those can be links from the eft menu. The slider it uses is graphic, so a post slider would require another plugin.

**Comment by GardnerCampbell** [comment] 2016-11-22 20:00
Thanks all -- heading into a meeting now, will investigate and respond
later on.

**Comment by woodwardtw** [comment] 2016-11-22 20:17
I wonder if that’s because of the weird redirect thing on Gardner’s site. 

The xmplrpc url ends up being http://www.gardnercampbell.net/blog1/xmlrpc.php http://www.gardnercampbell.net/blog1/xmlrpc.php
with the blog1 addition. I wonder if that’s enough to confuse FWP.

Tom

**Comment by GardnerCampbell** [comment] 2016-11-22 21:16
I may have the redirect set up clumsily. It's the first thing I did, 12 years ago: make it so www.gardnercampbell.net redirected to www.gardnercampbell.net/blog1 . Thing is, it's never been an issue with FWP to now.

I'll try the Feedburner thing. I've done that many times before, so unless they've changed something, I should be good to go.

**Comment by GardnerCampbell** [comment] 2016-11-22 21:24
OK, just got out of the meeting. Folks liked the site really well and were only slightly concerned about size--but see below. 

We also checked on iPad and iPhone and apparently Tom worked some kind of miracle, as these two actually display quite well. 

Now for the screenshots. I do think the font needs to be bumped up a bit. I understand that the ThoughtVectors site was fixed width, so that's fine--just my ignorance and forgetfulness talking. That said, you'll see from the two screenshots that the OpenLearningHub site could use a bigger font size. One screenshot is from one of Alice's blogs, just a standard WordPress blog with a default theme (I don't remember what 'year' the theme is but can check if needed). The other screenshot is from the Openlearninghub.net site. If it's possible to bump up the size without wrecking everything else with regard to mobile display, let's try it. If not, then I can live with this, and on we go. 

I do think we can stick with the ThoughtVectors theme for this iteration. Thanks.

You'll need to click on the screenshots below to compare the sizes. For some reason, GH resizes them so it appears the openlearninghub.net site has a larger font size than Alice's blog, which I do not think is the case.

If you want to see Alice's blog 'in the wild' so to speak, it's at http://www.justmusing.net/2013/11/22/turning-a-corner/

![alice blog screenshot](https://cloud.githubusercontent.com/assets/6348848/20542518/e256c7be-b0cf-11e6-9a75-6bad9c9b27e5.JPG)
![join-up screenshot](https://cloud.githubusercontent.com/assets/6348848/20542519/e2598c10-b0cf-11e6-8448-6409150741f3.JPG)

**Comment by woodwardtw** [comment] 2016-11-22 21:47
Font bumped to 1.2 em on paragraph text on desktops. May take a cache cleanse to see but I think it’s more what’s desired. I’ll go back and bump the size on lists etc. 

We can manipulate any of this independent of mobile views.

**Comment by cogdog** [comment] 2016-11-22 22:19
Glad we can work this out w/o theme change!

Tom- you are doing this through the stylesheet?  We are ignoring the theme settings (which are in fixed px sizes)? http://openlearninghub.net/wp-admin/admin.php?page=woothemes&tab=typography


We should be doing this as well on the sidebar widgets and menus. I get mixed up with em and rem sizing, thought this would help, but  https://j.eremy.net/confused-about-rem-and-em/

**Comment by GardnerCampbell** [comment] 2016-11-22 23:05
Wow. Rem and em. Who knew? This is really interesting stuff that it's cool to try to understand, the way I learned about signal-to-noise ratios by reading stereo magazines over and over until I got the context and the specifics. 

OK: I take it that 1.2 em is a 20% increase in font size relative to the nearest parent (or something like that). Can we try that at 1.1 please. Or 1.15 maybe. 1.2 is a little large.

I am sorry to be picky and needy. Be glad you're not my opthalmologist or optician. Things get real fun there.

**Comment by GardnerCampbell** [comment] 2016-11-22 23:06
Also, great to know this dimension can be tweaked independent of mobile views. I obviously came to the right voodoo team.

**Comment by cogdog** [comment] 2016-11-22 23:16
You may want to do some settings for the line-height as well. I use the inspector in chrome to fiddle, this is

````
@media (min-width: 701px), (max-width: 8300px)
.entry, .entry p {
    font-size: 1.1em;
    line-height: 1.4em;
}
````

![emem](https://cloud.githubusercontent.com/assets/463038/20545859/bc7a8cde-b0ce-11e6-80d0-fa896c152959.jpg)

If i get the em/rem understanding, if you define the classes with rem units, then you just use the `@media` breakpoints to define different base body font sizes. Otherwise you are explicitly doing ems for each break. I am only half guessing.

**Comment by cogdog** [comment] 2016-12-02 03:31
Closing issue. These should not be run on onversations. Open a new issue for a new topic, okie dokie?

**Closed as completed by cogdog** 2016-12-02 03:31 UTC
